src/SE/PlatformBundle/Entity/Comment.php
<?php

namespace SE\PlatformBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Context\ExecutionContextInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * Comment
 *
 * @ORM\Table(name="comment")
 * @ORM\Entity(repositoryClass="SE\PlatformBundle\Repository\CommentRepository")
 */
class Comment
{
    /**
     * @ORM\ManyToOne(targetEntity="SE\PlatformBundle\Entity\User")
     * @ORM\JoinColumn(name="user_sender", referencedColumnName="id", nullable=false)
     * @Assert\Valid()
     */
    protected $sender;

    /**
     * @ORM\ManyToOne(targetEntity="SE\PlatformBundle\Entity\User")
     * @ORM\JoinColumn(name="user_receiver", referencedColumnName="id", nullable=false)
     * @Assert\Valid()
     */
    protected $receiver;

    /**
     * @ORM\ManyToOne(targetEntity="SE\PlatformBundle\Entity\Advert")
     * @Assert\Valid()
     */
    private $advert;

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="content", type="text")
     */
    private $content;

    /**
     * @var int
     *
     * @ORM\Column(name="state", type="integer")
     */
    private $state;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="dateCreation", type="datetime")
     */
    private $dateCreation;

    /**
     * @var int
     *
     * @ORM\Column(name="rate", type="integer")
     */
    private $rate;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="dateUpdate", type="datetime", nullable=true)
     */
    private $dateUpdate;

    /**
     * @var bool
     *
     * @ORM\Column(name="isPublished", type="boolean")
     */
    private $isPublished;

    /**
     * @var bool
     *
     * @ORM\Column(name="isDeleted", type="boolean")
     */
    private $isDeleted;

    public function __construct()
    {
        $this->dateCreation=new \DateTime();

        $this->state = 0;
        $this->isPublished=1;
        $this->isDeleted=0;
    }


    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set content
     *
     * @param string $content
     *
     * @return Comment
     */
    public function setContent($content)
    {
        $this->content = $content;

        return $this;
    }

    /**
     * Get content
     *
     * @return string
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * Set state
     *
     * @param integer $state
     *
     * @return Comment
     */
    public function setState($state)
    {
        $this->state = $state;

        return $this;
    }

    /**
     * Get state
     *
     * @return integer
     */
    public function getState()
    {
        return $this->state;
    }

    /**
     * Set dateCreation
     *
     * @param \DateTime $dateCreation
     *
     * @return Comment
     */
    public function setDateCreation($dateCreation)
    {
        $this->dateCreation = $dateCreation;

        return $this;
    }

    /**
     * Get dateCreation
     *
     * @return \DateTime
     */
    public function getDateCreation()
    {
        return $this->dateCreation;
    }

    /**
     * Set rate
     *
     * @param integer $rate
     *
     * @return Comment
     */
    public function setRate($rate)
    {
        $this->rate = $rate;

        return $this;
    }

    /**
     * Get rate
     *
     * @return integer
     */
    public function getRate()
    {
        return $this->rate;
    }

    /**
     * Set dateUpdate
     *
     * @param \DateTime $dateUpdate
     *
     * @return Comment
     */
    public function setDateUpdate($dateUpdate)
    {
        $this->dateUpdate = $dateUpdate;

        return $this;
    }

    /**
     * Get dateUpdate
     *
     * @return \DateTime
     */
    public function getDateUpdate()
    {
        return $this->dateUpdate;
    }

    /**
     * Set isPublished
     *
     * @param boolean $isPublished
     *
     * @return Comment
     */
    public function setIsPublished($isPublished)
    {
        $this->isPublished = $isPublished;

        return $this;
    }

    /**
     * Get isPublished
     *
     * @return boolean
     */
    public function getIsPublished()
    {
        return $this->isPublished;
    }

    /**
     * Set isDeleted
     *
     * @param boolean $isDeleted
     *
     * @return Comment
     */
    public function setIsDeleted($isDeleted)
    {
        $this->isDeleted = $isDeleted;

        return $this;
    }

    /**
     * Get isDeleted
     *
     * @return boolean
     */
    public function getIsDeleted()
    {
        return $this->isDeleted;
    }

    /**
     * Set sender
     *
     * @param \SE\PlatformBundle\Entity\User $sender
     *
     * @return Comment
     */
    public function setSender(\SE\PlatformBundle\Entity\User $sender)
    {
        $this->sender = $sender;

        return $this;
    }

    /**
     * Get sender
     *
     * @return \SE\PlatformBundle\Entity\User
     */
    public function getSender()
    {
        return $this->sender;
    }

    /**
     * Set receiver
     *
     * @param \SE\PlatformBundle\Entity\User $receiver
     *
     * @return Comment
     */
    public function setReceiver(\SE\PlatformBundle\Entity\User $receiver)
    {
        $this->receiver = $receiver;

        return $this;
    }

    /**
     * Get receiver
     *
     * @return \SE\PlatformBundle\Entity\User
     */
    public function getReceiver()
    {
        return $this->receiver;
    }

    /**
     * Set advert
     *
     * @param \SE\PlatformBundle\Entity\Advert $advert
     *
     * @return Comment
     */
    public function setAdvert(\SE\PlatformBundle\Entity\Advert $advert = null)
    {
        $this->advert = $advert;

        return $this;
    }

    /**
     * Get advert
     *
     * @return \SE\PlatformBundle\Entity\Advert
     */
    public function getAdvert()
    {
        return $this->advert;
    }
}

src/SE/PlatformBundle/Form/CommentType.php
<?php

namespace SE\PlatformBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FormType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class CommentType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder

                ->add('rate', ChoiceType::class, array('label'=> "Note de l'avis *",
                      'placeholder' => "Note de l'avis",
                            'choices' => array(
                                        'À éviter - 1/5' => '1',
                                        'Décevant - 2/5' => '2',
                                        'Bien - 3/5' =>  '3' ,
                                        'Très bien - 4/5' => '4',
                                        'Parfait - 5/5' => '5'
                            ),
                            'required'    => true
                        ))
                        ->add('content', TextareaType::class, array('label'=> "Commentaire de l'avis *"))


                 ->add('save', SubmitType::class,
                                array('label'=> 'Envoyer',
                                    'attr'   =>  array(
                                                'class'   => 'btn btn-primary btn-block')));
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'SE\PlatformBundle\Entity\Comment'
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'se_platformbundle_comment';
    }


}

src/SE/PlatformBundle/Controller/CommentController.php
<?php

namespace SE\PlatformBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use SE\PlatformBundle\Entity\Comment;
use SE\PlatformBundle\Form\CommentType;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

class CommentController extends Controller
{
    /* PRIVATE VAR */
    private $nbPerPage = 20;
    private $em;
    private $state;

    /* PRIVATE FUNCTION */
    private function getDoctrineManager(){
      return $this->getDoctrine()->getManager();
    }

    private function getListUserFilterAttributes(Request $request){
        $this->state = $request->query->get('state');
    }

    private function getCommentState(){
      $em = $this->getDoctrineManager();
      return $em->getRepository('SEPlatformBundle:CommentState')->findAll();
    }
    /* PUBLIC FUNCTION */

    /**
     * @Security("has_role('ROLE_AUTEUR')")
     */
     public function addAction(Request $request, $advertId, $auctionUserId){

         $em = $this->getDoctrineManager();
         $session = $request->getSession();
         $mailer  = $this->get('se_platform.mailer');

         $advert=$em->find('SEPlatformBundle:Advert', $advertId);
         $advert->setIsPublished(false);
         $userReceiver = $em->find('SEPlatformBundle:User', $auctionUserId);

         $userSender = $this->getUser();

         if ($userSender == $advert->getUser()) {
             $comment = new Comment();

             $form = $this->createForm(CommentType::class, $comment);

             if ($request->isMethod('POST')){
                 $form->handleRequest($request);

                 if ($form->isValid() && $comment->getContent() !== NULL && $comment->getContent() !== ''){

                       $rate = $comment->getRate();

                       $listComment = $em
                                   ->getRepository('SEPlatformBundle:Comment')
                                   ->getComment($userReceiver->getId(), false);
                       $countComment = count($listComment) + 1;

                       foreach ($listComment as $item) {
                           $rate = $rate + $item->getRate();
                       }

                       $rate = $rate / $countComment;

                       $userReceiver->setRate(round($rate));

                       $advert->setCommentState(1);

                       $comment->setSender($userSender);
                       $comment->setAdvert($advert);
                       $comment->setReceiver($userReceiver);

                       $em->persist($advert);
                       $em->persist($comment);
                       $em->flush();

                       $body = $this->renderView(
                              'SEPlatformBundle:Comment:addMail.html.twig',
                              array( 'receiver' => $userReceiver,
                                     'advert'=> $advert)
                          );

                       $mailer->sendEmail('Avis reçu', 'Vous avez reçu un avis', $userReceiver->getEmail(), $body);

                       $session->getFlashBag()->add('addSuccess','Avis bien ajouté.');

                       return $this->redirectToRoute('se_platform_advert_user_list');
                     }
                     else{
                       $session->getFlashBag()->add('warning','Votre message est vide.');
                     }
             }
         }
         else {
             throw new NotFoundHttpException("Oops, Vous n'êtes pas le propriétaire de la demande.");
         }

         return $this->render('SEPlatformBundle:Comment:add.html.twig', array(
             'form' => $form->createView(),
             'advert'=>$advert
         ));
     }

    /**
     * @Security("has_role('ROLE_AUTEUR')")
     */
     public function editAction($id, Request $request){

       $em = $this->getDoctrineManager();
       $session = $request->getSession();
       $comment=$em->find('SEPlatformBundle:Comment', $id);
       $userReceiver = $em->find('SEPlatformBundle:User', $comment->getReceiver()->getId());
       $userSender = $em->find('SEPlatformBundle:User', $comment->getSender()->getId());

       if (null===$comment or null===$userReceiver){
             throw new NotFoundHttpException("Oops, L avis  que vous cherchez n'existe pas.");
         }

         if ($this->getUser() === $userSender) {

             $form = $this->createForm(CommentType::class, $comment);

             if ($request->isMethod('POST')){

                 $form->handleRequest($request);
                 if ($form->isValid()){

                   $rate = $comment->getRate();

                   $listComment = $em
                               ->getRepository('SEPlatformBundle:Comment')
                               ->getComment($userReceiver->getId(), false);

                   $countComment = count($listComment) + 1;

                   foreach ($listComment as $item) {
                       $rate = $rate + $item->getRate();
                   }

                   $rate = $rate / $countComment;

                   $userReceiver->setRate(round($rate));

                     $comment->setDateUpdate(new \DateTime());
                     $em->flush();

                     $session->getFlashBag()->add('editSuccess','Avis modifié avec succes');

                     return $this->redirectToRoute('se_platform_comment_edit',
                                 array('id'=>$comment->getId()));
                 }
               }
           }
           else {
               throw new NotFoundHttpException("Oops, Vous n'êtes pas le propriétaire de la demande.");
           }
         return $this->render('SEPlatformBundle:Comment:edit.html.twig', array(
             'form' => $form->createView(),
             'comment'=>$comment
         ));
     }

     /**
      * @Security("has_role('ROLE_SUPER_ADMIN')")
      */
    public function deleteAction($id, Request $request){
      $em = $this->getDoctrineManager();
      $session = $request->getSession();
      $comment = $em->getRepository('SEPlatformBundle:Comment')->find($id);
      $userSender = $em->find('SEPlatformBundle:User', $comment->getSender()->getId());

       if (null===$comment){
            throw new NotFoundHttpException("Oops, L'avis que vous cherchez n'existe pas.");
        }

        if ($this->getUser() === $userSender) {

        $form = $this->createFormBuilder()->getForm();

        if ($form->handleRequest($request)->isValid()) {

            $comment->setIsDeleted(true);
            $comment->setIsPublished(false);
            $comment->setDateUpdate(new \DateTime());

            $em->flush();

            $request->getSession()->getFlashBag()->add('deleteSuccess', "L avis a bien été supprimée.");

            return $this->redirectToRoute('se_platform_advert_validate', array('action'=>'supprimer'));
        }

      }
      else {
          throw new NotFoundHttpException("Oops, Vous n'êtes pas le propriétaire de la demande.");
      }

        return $this->render('SEPlatformBundle:Comment:delete.html.twig', array(
            'comment' => $comment,
            'form'   => $form->createView()
        ));
    }

    /**
     * @Security("has_role('ROLE_AUTEUR')")
     */
    public function listUserAction(Request $request, $page){
        $user = $this->getUser();
        $this->getListUserFilterAttributes($request);

        $listComment = $this->getDoctrine()
            ->getManager()
            ->getRepository('SEPlatformBundle:Comment')
            ->getCommentListUser($user->getId(), $this->state, $page, $this->nbPerPage);

        $titleResult = count($listComment) == 0 ? 'Aucun avis' : count($listComment).' avis';

        $nbPages = ceil(count($listComment)/$this->nbPerPage);

        if ($page<1){
            throw new NotFoundHttpException('page"'.$page.'" inexistante');
        }

      return $this->render('SEPlatformBundle:Comment:listUser.html.twig',
          array(
            'nbPages'     => $nbPages,
            'page'        => $page,
            'listComment'=> $listComment,
            'countComment'=> $titleResult,
            'state'=> $this->state,
            'listCommentState'=>$this->getCommentState()
          ));
    }

    public function countRateAction($rate, $user){
        $em = $this->getDoctrineManager();

        $countRate = $em
            ->getRepository('SEPlatformBundle:Comment')
            ->getCommentByRate($rate, $user);


        return new Response(
            count($countRate)
        );
    }

    public function progressRateAction($rate, $user){
        $em = $this->getDoctrineManager();

        $countRate = $em
            ->getRepository('SEPlatformBundle:Comment')
            ->getCommentByRate($rate, $user);

      $listComment = $this->getDoctrine()
          ->getManager()
          ->getRepository('SEPlatformBundle:Comment')
          ->getCommentListUser($user, '2', 1, 100000000);

          $progress = 0;
          if (count($listComment) != 0) {
            $progress =   (count($countRate) * 100) / count($listComment);
          }

        return new Response(
          $progress
        );
    }
}

src/SE/PlatformBundle/Resources/views/Comment/add.html.twig
{% extends "SEPlatformBundle::layout.html.twig" %}

{% block title %}
  Ajouter un avis pour la demande {{advert.title}}
{% endblock %}
{% block description %}
  <meta name="description" content="Vous êtes satisfait ou pas de la prestation, exprimez vous en ajoutant un avis." />
{% endblock %}

{% block layout_header2 %}
<div class="row">
  <div id="header" class="col-md-12">
      <h3 class="cat-title">Ajouter un avis</h3>
  </div>
</div>
{% endblock %}
{% block layout_body %}
  <div class="row">
    {% if app.user.isAcountComplete == 0 %}
        <div class="alert alert-warning" role="alert">
            Bonjour {{ app.user.username }}, Votre profil n'est pas complet, merci de le
            <a class="alert-link" href="{{ path('fos_user_profile_edit') }}" >compléter</a>
        </div>
    {% else %}
      <div id="content" class="col-md-3"></div>
       <div id="content" class="col-md-6">
         {% if advert.commentState  %}
         <div class="alert alert-info text-center" role="alert">
         </p>Vous avez déjà laissé un avis à ce artisan</p>
         <a href="{{path('se_platform_comment_user_list')}}">Voir mes avis.</a>
         </div>

         {% else %}
         <div class="alert alert-danger" role="alert">
             Après l'ajout de cet avis, la demande sera désactivée sur le site.
             <br>
             Si la demande est toujours d'actualité <b>quittez cette page</b>.
         </div>
           {{ include('SEPlatformBundle:Comment:form.html.twig') }}
         {% endif %}
       </div>
      <div id="content" class="col-md-3"></div>
 {% endif %}
   </div>
{% endblock %}

src/SE/PlatformBundle/Resources/views/Comment/addMail.html.twig
{% extends 'SEPlatformBundle::mailLayout.html.twig' %}

{% block mail_header %} {{ include('@SEPlatform/Mail/header.html.twig') }} {% endblock %}
{% block mail_content %} {{ include('@SEPlatform/Mail/Comment/add.html.twig') }} {% endblock %}
{% block mail_footer %} {{ include('@SEPlatform/Mail/footer.html.twig') }} {% endblock %}

src/SE/PlatformBundle/Resources/views/Comment/delete.html.twig
{% extends "SEPlatformBundle::layout.html.twig" %}

{% block title %}
  Supprimer un avis laissé
{% endblock %}
{% block description %}
  <meta name="description" content="Ne supprimez pas l'avis, modifiez le." />
{% endblock %}

{% block layout_header2 %}
<div class="row">
  <div id="header" class="col-md-12">
      <h3 class="cat-title">Supprimer un avis</h3>
  </div>
</div>
{% endblock %}
{% block layout_body %}
<div class="row">
     <div id="content" class="col-md-12">
       <div class="col-md-6">
            <p class="pad-msg">Etes-vous certain de vouloir supprimer l'avis ?</p>
            <div class="col-md-6">
              <a href="{{ path('se_platform_comment_user_list') }}" class="form-control btn btn-primary">
                  Retour à mes avis
              </a>
            </div>
            <div class="col-md-6">
                <form action="{{ path('se_platform_comment_delete', {'id': comment.id}) }}" method="post">
                    <input type="submit" value="Supprimer" class="btn btn-danger" />
                    {{ form_rest(form) }}
                </form>
            </div>
        </div>
     </div>
 </div>
{% endblock %}

src/SE/PlatformBundle/Resources/views/Comment/edit.html.twig
{% extends "SEPlatformBundle::layout.html.twig" %}

{% block title %}
  Modifier un avis laissé
{% endblock %}
{% block description %}
  <meta name="description" content="Consultez la page des artisans, avant de modifiez l'avis." />
{% endblock %}


{% block layout_header2 %}
  <div class="row">
    <div id="header" class="col-md-12">
        <h3 class="cat-title">Modifier un avis</h3>
    </div>
  </div>
{% endblock %}
{% block layout_body %}
<div class="col-md-3"></div>
<div class="col-md-6">

         {% for flash_message in app.session.flashBag.get('editSuccess') %}
             <div class="alert alert-success text-center" role="alert">
               <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                 {{ flash_message }}
             </div>
         {% endfor %}

            {{ include('SEPlatformBundle:Comment:form.html.twig') }}
         </div>

 <div  class="col-md-3"></div>

{% endblock %}

src/SE/PlatformBundle/Resources/views/Comment/form.html.twig
    {{ form(form) }}

src/SE/PlatformBundle/Resources/views/Comment/listUser.html.twig
{% extends "SEPlatformBundle::layout.html.twig" %}

{% block title %}
    Mes avis laisés et reçus sur Top Artisan
{% endblock %}
{% block description %}
  <meta name="description" content="Consultez votre profil pour voir l'aperçu sur Top Artisan." />
{% endblock %}

{% block layout_header2 %}
<div class="row">
  <div id="header" class="col-md-12">
    <h3 class="cat-title">Mes avis</h3>
    {{ include('@SEPlatform/Comment/listUserFilter.html.twig') }}
  </div>
</div>

{% endblock %}
{% block layout_body %}

<div class="row">
  <div class="col-md-12">
    {% if app.user.isAcountComplete == 0 %}
        <div class="alert alert-warning" role="alert">
            Bonjour {{ app.user.username }}, Votre profil n'est pas complet, merci de le
            <a class="alert-link" href="{{ path('fos_user_profile_edit') }}" >compléter</a>
        </div>
    {% else %}
    <h4 class="cat-title">{{countComment}}</h4>

    {% for comment in listComment %}
          <div class="review-block">
            <div class="row">
              <div class="col-sm-3">
                <h5>{% if app.user == comment.receiver %}<span class="label label-success">Avis reçu</span>
                {% else %}
                  <span class="label label-primary">Avis laissé</span>
                {% endif %}</h5>
                <i class="glyphicon glyphicon-user se-user-icon"></i>
                <div class="review-block-name">
                    {% if app.user == comment.receiver %}
                      <a class="cat-link"
                          href="{{ path('se_platform_user_view', {'userId': comment.sender.id}) }}"
                          >{{ comment.sender }}</a>
                    {% else %}

                    <a class="cat-link"
                        href="{{ path('se_platform_user_view', {'userId': comment.receiver.id}) }}"
                        >{{ comment.receiver }}</a>
                    {% endif %}
                </div>
                <div class="review-block-date">{{ comment.dateCreation|date('d/m/Y') }}</div>
              </div>
              <div class="col-sm-9">
                  <div class="review-block-rate">
                    {{ include('@SEPlatform/User/small-rate.html.twig', {'item': comment }) }}
                  </div>
                  <div class="review-block-title">{{ comment.advert.title }}</div>
                  <div class="review-block-description"><h5>{{ comment.content |nl2br }}</h5></div>
                  {% if app.user == comment.sender %}
                       <div class='text-right'>
                         <a href="{{ path('se_platform_comment_edit', {'id': comment.id}) }}"
                         type="button"
                         class='btn btn-success'
                         title="Modifier">
                         Modifier
                         </a>
                       </div>
                 {% endif %}
              </div>
            </div>
          </div>
    {% endfor %}
      {% endif %}
  </div>
</div>

   <div class="row">
       <div class="col-md-12 text-center">
           <ul class="pagination">
               {% if nbPages > 1 %}
                   {% for p in range(1, nbPages) %}
                       <li{% if p == page %} class="active"{% endif %}>
                           <a href="{{ path('se_platform_comment_user_list', {'page': p}) }}">{{ p }}</a>
                       </li>
                   {% endfor %}
               {% endif %}
           </ul>
       </div>
   </div>
{% endblock %}

src/SE/PlatformBundle/Resources/views/Comment/listUserFilter.html.twig
    <form id="form_recherche" action="" method="get">
        <div class="form-group">
            <div class="row">
                <div class="col-md-4 filter">
                        <select class="form-control"
                                name="state"
                                id="state_id" >
                            <option value='0' >Tous les avis</option>
                              {% for state in listCommentState %}
                                  <option {{ app.request.query.get('state')== state.id ? ' selected ' : ' ' }}
                                      value={{ state.id }}>{{ state.labelNormal }}
                                  </option>
                              {% endfor %}
                        </select>
                </div>

                <div class="col-md-4 filter">
                    <input class="btn btn-lg-se btn-primary" type="submit" value="Afficher"  />
                </div>
                <div class="col-md-4 filter">
                  <a href="{{ path('se_platform_comment_user_list') }}"
                            type="button" class="btn btn-lg-se btn-primary" >
                             Réinitialiser
                  </a>
                </div>
              </div>
        </div>
    </form>

src/SE/PlatformBundle/Resources/views/Comment/userList.html.twig
{% extends "SEPlatformBundle::layout.html.twig" %}

{% block title %}
    Mes cmomentaires - {{ parent() }}
{% endblock %}

{% block layout_header2 %}
  <div class="col-md-12">
      <h3 class="cat-title">Filter</h3>
  </div>
{% endblock %}
{% block layout_body %}
  <div class="row">
       <div id="content" class="col-md-12">
         Mes commentaires
       </div>
   </div>
{% endblock %}